// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: contracts/v1/record.proto

package record_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EndpointsClient is the client API for Endpoints service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EndpointsClient interface {
	Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error)
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error)
	ConsumeStream(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (Endpoints_ConsumeStreamClient, error)
	ProduceStream(ctx context.Context, opts ...grpc.CallOption) (Endpoints_ProduceStreamClient, error)
}

type endpointsClient struct {
	cc grpc.ClientConnInterface
}

func NewEndpointsClient(cc grpc.ClientConnInterface) EndpointsClient {
	return &endpointsClient{cc}
}

func (c *endpointsClient) Produce(ctx context.Context, in *ProduceRequest, opts ...grpc.CallOption) (*ProduceResponse, error) {
	out := new(ProduceResponse)
	err := c.cc.Invoke(ctx, "/record.v1.Endpoints/Produce", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointsClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error) {
	out := new(ConsumeResponse)
	err := c.cc.Invoke(ctx, "/record.v1.Endpoints/Consume", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *endpointsClient) ConsumeStream(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (Endpoints_ConsumeStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Endpoints_ServiceDesc.Streams[0], "/record.v1.Endpoints/ConsumeStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &endpointsConsumeStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Endpoints_ConsumeStreamClient interface {
	Recv() (*ConsumeResponse, error)
	grpc.ClientStream
}

type endpointsConsumeStreamClient struct {
	grpc.ClientStream
}

func (x *endpointsConsumeStreamClient) Recv() (*ConsumeResponse, error) {
	m := new(ConsumeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *endpointsClient) ProduceStream(ctx context.Context, opts ...grpc.CallOption) (Endpoints_ProduceStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Endpoints_ServiceDesc.Streams[1], "/record.v1.Endpoints/ProduceStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &endpointsProduceStreamClient{stream}
	return x, nil
}

type Endpoints_ProduceStreamClient interface {
	Send(*ProduceRequest) error
	Recv() (*ProduceResponse, error)
	grpc.ClientStream
}

type endpointsProduceStreamClient struct {
	grpc.ClientStream
}

func (x *endpointsProduceStreamClient) Send(m *ProduceRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *endpointsProduceStreamClient) Recv() (*ProduceResponse, error) {
	m := new(ProduceResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EndpointsServer is the server API for Endpoints service.
// All implementations must embed UnimplementedEndpointsServer
// for forward compatibility
type EndpointsServer interface {
	Produce(context.Context, *ProduceRequest) (*ProduceResponse, error)
	Consume(context.Context, *ConsumeRequest) (*ConsumeResponse, error)
	ConsumeStream(*ConsumeRequest, Endpoints_ConsumeStreamServer) error
	ProduceStream(Endpoints_ProduceStreamServer) error
	mustEmbedUnimplementedEndpointsServer()
}

// UnimplementedEndpointsServer must be embedded to have forward compatible implementations.
type UnimplementedEndpointsServer struct {
}

func (UnimplementedEndpointsServer) Produce(context.Context, *ProduceRequest) (*ProduceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Produce not implemented")
}
func (UnimplementedEndpointsServer) Consume(context.Context, *ConsumeRequest) (*ConsumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedEndpointsServer) ConsumeStream(*ConsumeRequest, Endpoints_ConsumeStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ConsumeStream not implemented")
}
func (UnimplementedEndpointsServer) ProduceStream(Endpoints_ProduceStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ProduceStream not implemented")
}
func (UnimplementedEndpointsServer) mustEmbedUnimplementedEndpointsServer() {}

// UnsafeEndpointsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EndpointsServer will
// result in compilation errors.
type UnsafeEndpointsServer interface {
	mustEmbedUnimplementedEndpointsServer()
}

func RegisterEndpointsServer(s grpc.ServiceRegistrar, srv EndpointsServer) {
	s.RegisterService(&Endpoints_ServiceDesc, srv)
}

func _Endpoints_Produce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointsServer).Produce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/record.v1.Endpoints/Produce",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointsServer).Produce(ctx, req.(*ProduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Endpoints_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EndpointsServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/record.v1.Endpoints/Consume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EndpointsServer).Consume(ctx, req.(*ConsumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Endpoints_ConsumeStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConsumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EndpointsServer).ConsumeStream(m, &endpointsConsumeStreamServer{stream})
}

type Endpoints_ConsumeStreamServer interface {
	Send(*ConsumeResponse) error
	grpc.ServerStream
}

type endpointsConsumeStreamServer struct {
	grpc.ServerStream
}

func (x *endpointsConsumeStreamServer) Send(m *ConsumeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Endpoints_ProduceStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EndpointsServer).ProduceStream(&endpointsProduceStreamServer{stream})
}

type Endpoints_ProduceStreamServer interface {
	Send(*ProduceResponse) error
	Recv() (*ProduceRequest, error)
	grpc.ServerStream
}

type endpointsProduceStreamServer struct {
	grpc.ServerStream
}

func (x *endpointsProduceStreamServer) Send(m *ProduceResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *endpointsProduceStreamServer) Recv() (*ProduceRequest, error) {
	m := new(ProduceRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Endpoints_ServiceDesc is the grpc.ServiceDesc for Endpoints service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Endpoints_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "record.v1.Endpoints",
	HandlerType: (*EndpointsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Produce",
			Handler:    _Endpoints_Produce_Handler,
		},
		{
			MethodName: "Consume",
			Handler:    _Endpoints_Consume_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConsumeStream",
			Handler:       _Endpoints_ConsumeStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ProduceStream",
			Handler:       _Endpoints_ProduceStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "contracts/v1/record.proto",
}
